- block:
    - name: Decompress AMQ Broker artifact package into the target directory
      unarchive:
        src: "{{ payload.artifact_name }}"
        remote_src: "{{ common.remote_src }}"
        dest: "{{ amq.install_dir }}"
        owner: "{{ amq.username }}"
        group: "{{ amq.group }}"
        mode: "{{ amq.install_dir_mode }}"
  tags:
    - amq::decompress
