- block:
    - name: Add the AMQ Broker unix group
      group:
        name: "{{ amq.group }}"
        gid: "{{ amq.group_id }}"
        state: present

    - name: Add and configure the AMQ Broker user
      user:
        name: "{{ amq.username }}"
        comment: "{{ amq.user_comment }}"
        uid: "{{ amq.user_uid }}"
        group: "{{ amq.group }}"

    - name: Create and setup the AMQ Broker software installation path
      file:
        path: "{{ amq.install_dir }}"
        owner: "{{ amq.username }}"
        group: "{{ amq.group }}"
        mode: "{{ amq.install_dir_mode }}"
        state: directory
  tags:
    - amq::preconfig
