# AMQ BROKER INSTALLATION PLAYBOOK

- hosts: broker_dev
  remote_user: root
  become: no
  any_errors_fatal: true

  pre_tasks:
    - include_vars:
        file: "common"
    - include_vars:
        file: "environments/dev"
    - include_vars:
        file: "credentials/customerportal"
  roles:
    - amq-broker
