- block:
    - name: Render AMQ Broker Configuration templates
      template:
        src: "amq-broker/{{ item }}.j2"
        dest: "{{ parameters.instance_etc_dir }}/{{ item }}"
        owner: "{{ amq.username }}"
        group: "{{ amq.group }}"
        backup: True
      loop:
        - artemis.profile
        - bootstrap.xml
        - broker.xml
        - jgroups-file_ping.xml
        - logging.properties
        - login.config
        - management.xml
        - queue-security-settings.xml
        - addresses-settings.xml
        - addresses.xml
  tags:
    - amq::broker_configuration_render_templates
