- block:
    - name: Copy Users and Roles creation script
      copy:
        src: "files/add_users_roles.sh"
        dest: "/tmp/add_users_roles.sh"
        backup: False
        owner: "{{ amq.username }}"
        group: "{{ amq.group }}"
        mode: "u+rwx,g+rw,o="
    - name: Add Users and Roles to the Broker Instance
      command: >
        /tmp/add_users_roles.sh {{ parameters.instance_dir }} {{ item.username }} {{ item.password }} {{ item.role }} {{ admin_user.username }} {{ admin_user.password }}| grep CREATED
      loop:
        "{{ amq_users }}"
      register: user_config
      changed_when: user_config.stdout == 'CREATED'
  tags:
    - amq::broker_configuration_users_and_roles
