---
- name: Install systemd service
  template:
    src: "etc/systemd/system/amq-broker.service.j2"
    dest: "/etc/systemd/system/amq-broker.service"
  register: systemd_unit_install

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_unit_install.changed

- name: Enable AMQ-Broker service
  systemd:
    name: amq-broker
    enabled: yes
    masked: no

- name: Start AMQ-Broker service
  debug:
    msg: "Restarting AMQ Broker... {{ amq.broker_name }}"
  notify: Start broker service
  when: amq.restart_service == 'yes'
