---
- name: Install systemd service
  template:
    src: "etc/systemd/system/amq-broker.service.j2"
    dest: "/etc/systemd/system/amq-broker.service"
  register: systemd_unit_install

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_unit_install.changed

- name: Enable AMQ-Broker service
  systemd:
    name: amq-broker
    enabled: yes
    state: started
    masked: no

- name: Wait for Artemis Acceptor to come up
  ansible.builtin.wait_for:
    host: "{{ ipv4.listen_address_for_acceptors }}"
    port: "{{ ports.artemis }}"
    timeout: 60
    delay: 10

- name: Start AMQ-Broker service
  debug:
    msg: "Restarting AMQ Broker... {{ amq.broker_name }}"
  notify: Start broker service
  when: amq.restart_service == 'yes'
